---
title: "Rethinking the role of genomics and methylomics analysis in brain tumour subtyping"
author: "Yuanhao Jiang"
date: 07/30/2024
editor: visual
toc: true
format:
  html:
    self-contained: true
execute:
  warning: false
---

# Introduction

We are in the era of precision medicine, where the treatment of diseases is tailored to the individual patient based on their unique genetic and molecular characteristics. In the field of oncology, this approach has led to significant advances in the diagnosis and treatment of cancer, with targeted therapies and immunotherapies becoming increasingly common. However, the complexity and heterogeneity of cancer present challenges for accurate diagnosis and treatment selection, particularly in brain tumours.

In this review, we will explore the role of genomics and methylomics analysis in brain tumour subtyping, and how these techniques can improve our understanding of tumour biology and guide personalized treatment strategies.

We will discuss the current landscape of brain tumour classification, the limitations of traditional histopathological methods, and the potential of genomic and epigenomic profiling to overcome these challenges.

We will also highlight recent advances in the field, including the identification of novel molecular subtypes and the development of predictive biomarkers for treatment response.

# Notes for the literature collection

The note includes two parts: the overview of the paper generated by `OpenRead` and the benefits for literature review summarised by my self.

1.  [A deep learning system accurately classifies primary and metastatic cancers using passenger mutation patterns](../scripts/Literature_review/A%20deep%20learning%20system%20accurately%20classifies%20primary%20and%20metastatic%20cancers%20using%20passenger%20mutation%20patterns.html)
