---
title: "ReadME"
author: "Yuanhao"
date: 07/30/2024
editor: visual
toc: true
format:
  html:
    self-contained: true
execute:
  warning: false
---

# Intro

Differential methylation analysis is powered by two comprehensive pipeline, `RnBeads` and customised `Cross-packages` pipeline. The `RnBeads` is used to generate a quick general overview of methylation data. We developed a `Cross-packages` analytical approaches to perform deeper analysis.

# RnBeads workflow

RnBeads includes six components to conduct the comprehensive analysis.

The link below is currently unavailable due to the limitation of file size. We will handle this issue once we have significant progress.

-   [Data import]()

-   [Quality control]()

-   [Preprocessing]()

-   [Covariate inference]()

-   [Exploratory analysis]()

-   [Differential methylation]()

# Cross-packages workflow

We develop a `cross-packages` analytical approach which is tailered for `EPICv2` array. We have done some preliminary differential analysis including:

-   [DMG vs Non DMG](./DMG_vs_Non_DMG.html)

-   [DMG vs Non DMG brain tumor](./DMG_vs_Non_DMG_BrainTumor.html)

-   [DMG vs Normal](./DMG_vs_Normal.html)

-   [DMG vs Giolblastoma](./DMG_vs_Giolblastoma.html).

The outlline of workflow can be found here:

-   Data loading
-   Quality control
-   Preprocessing
    -   Pre-filtering
    -   Normalisation
    -   Post-filtering
    -   SVD analysis
    -   Batch correction
-   Probe-wise differential analysis
    -   Differential CpG sites identification
    -   Sample-wise methylation visualisation
    -   Probe-wise volcano plot
    -   Heatmap of differential methylated CpG sites
    -   Pathway enrichment analysis
-   Differential methylation analysis of regions
-   Differential variability analysis
    -   Differential CpG sites identification
    -   Sample-wise methylation visualisation
    -   Probe-wise volcano plot
    -   Heatmap of differential methylated CpG sites
    -   Pathway enrichment analysis
-   Integrative pathway enrichment analysis
    -   Used the intersection of differential CpG sites from probe-wise differential analysis and differential variability analysis.
    -   The integrated CpGs showcase significance in both mean and variance differential testing which provide robust performance on pathway analysis.
